_wandb:
    value:
        cli_version: 0.28.1
        e:
            ruvblec6b7ests90y9wjwaab6of6gs79:
                codePath: src/wandb-test.py
                codePathLocal: src/wandb-test.py
                email: mckenzie.amber@gmail.com
                executable: /Users/docam/VSCode/toy-text-classifier/toy-text-classifier/.venv/bin/python
                git:
                    commit: 616dff4d300a8655607e675ed339d1ae10cb0cdc
                    remote: https://github.com/ab6/toy-text-classifier.git
                host: Ambers-MBP.home.local
                os: macOS-26.4.1-arm64-arm-64bit-Mach-O
                program: /Users/docam/VSCode/toy-text-classifier/toy-text-classifier/src/wandb-test.py
                python: CPython 3.14.4
                root: /Users/docam/VSCode/toy-text-classifier/toy-text-classifier
                startedAt: "2026-07-23T21:49:41.524562Z"
                writerId: ruvblec6b7ests90y9wjwaab6of6gs79
        m: []
        python_version: 3.14.4
        t:
            "3":
                - 2
                - 16
            "4": 3.14.4
            "5": 0.28.1
            "12": 0.28.1
            "13": darwin-arm64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
